CREATE TABLE IF NOT EXISTS song(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    album VARCHAR(255) NOT NULL,
    length VARCHAR(255) NOT NULL,
    year VARCHAR(255) NOT NULL,
    resource_id INTEGER NOT NULL
);