server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    instance:
      prefer-ip-address: true

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/
